apiVersion: v1
kind: Service
metadata:
  name: rabbitmq2
  labels:
    app: rabbitmq2
    type: LoadBalancer
spec:
  selector:
    app: rabbitmq2
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31671
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30671
  type: NodePort