server:
  port: 8086

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: client
          uri: lb://CLIENT
          predicates:
            - Path=/api/v1/client/add
        - id: client
          uri: lb://CLIENT
          predicates:
            - Path=/api/v1/client/find

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true