server:
  port: 8081
spring:
  application:
    name: check
  datasource:
    url: jdbc:postgresql://localhost:5432/check
    password: password
    username: Farzan
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true