server:
  port: 8082
spring:
  application:
    name: client

  zipkin:
    base-url: http://localhost:9411

  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/client
    username: Farzan
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
