server:
  port: 8082
spring:
  application:
    name: client

  zipkin:
    base-url: http://zipkin2:9411

  rabbitmq:
    addresses: rabbitmq2:5672

  datasource:
    password: password
    url: jdbc:postgresql://postgres2:5432/client
    username: Farzan
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server2:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
