apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres2
  labels:
    app: postgres2
spec:
  serviceName: postgres2
  replicas: 1
  selector:
    matchLabels:
      app: postgres2
  template:
    metadata:
      name: postgres2
      labels:
        app: postgres2
    spec:
      volumes:
        - name: postgres2
          persistentVolumeClaim:
            claimName: postgres-pc-volume-claim-2
      containers:
        - name: postgres2
          image: postgres
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres2
          envFrom:
            - configMapRef:
                name: postgres-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
