apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pc-volume-2
  labels:
    type: local
    app: postgres2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pc-volume-claim-2
  labels:
    app: postgres2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi