apiVersion: apps/v1
kind: Deployment
metadata:
  name: check
  labels:
    app: check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check
  template:
    metadata:
      name: check
      labels:
        app: check
    spec:
      containers:
        - name: check
          image: farzanfarzan/check:new
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
